Move grape
SSconnect/SSConnectAPI pull request #27
Opened 2017-04-06 02:12 UTC by atsuo1203

apiをgrapeに移行

2017-04-06 02:38 UTC, elzup requested changes

2017-04-06 02:38 UTC, elzup commented on app/controllers/v1/blogs_controller.rb
> +    prefix :api
https://github.com/DisasterMeshVisualiser/api/blob/master/app/apis/api/v1/root.rb

module V1 のトップに Root クラス作って mount しておくと
共通の定義(content_type, version, format, prefix) を一度書くだけで済むよ

2017-04-06 02:38 UTC, elzup commented on app/controllers/v1/blogs_controller.rb
> +      desc 'blog all'
desc は 'GET /hoges/:id' とか 'POST /peoples' の記法が使いたいかも

2017-04-06 02:38 UTC, elzup commented on app/controllers/v1/blogs_controller.rb
> +         @blog
下の行いらないはず

2017-04-06 02:38 UTC, elzup commented on app/controllers/v1/stories_controller.rb
> +        tag = params[:tag] || ''
params 使っていこう
https://github.com/ruby-grape/grape#supported-parameter-types

```
desc ...
params do
  optional :page, type: Integer, default: 1
  optional :q, type: String
  optional :tag, type: String
end
get do ...
```

2017-04-07 01:20 UTC, atsuo1203 commented on app/controllers/v1/blogs_controller.rb
> +         @blog
修正しました！

2017-04-07 01:20 UTC, atsuo1203 commented on app/controllers/v1/stories_controller.rb
> +        tag = params[:tag] || ''
修正しました！

2017-04-07 03:09 UTC, elzup commented
desc はそれぞれ

GET /articles
GET /articles/:id
GET /blogs
GET /blogs/:id
GET /stories
GET /stories/:id
GET /tags
GET /tags/:id
で

2017-04-07 04:03 UTC, elzup approved these changes

2017-04-07 04:03 UTC, merged